# Project information
site_name: Agent Development Kit
site_url: https://google.github.io/adk-docs
site_description: >-
  Build powerful multi-agent systems with Agent Development Kit
site_dir: site
exclude_docs:
  api-reference/java/legal/*

# Repository
repo_name: adk-python
repo_url: https://github.com/google/adk-python

# Copyright
copyright: Copyright Google 2025

# Custom CSS
extra_css:
  - stylesheets/custom.css

extra:
  second_repo_url: https://github.com/google/adk-java
  second_repo_name: adk-java
  second_repo_icon: fontawesome/brands/github

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true


# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'get-started/testing.md'
        'get-started/tutorial.md': 'tutorials/index.md'
        'guides/responsible-agents.md': 'safety/index.md'

# Navigation
nav:
  - Home: index.md
  - Get Started:
    - get-started/index.md
    - Installation: get-started/installation.md
    - Quickstart: get-started/quickstart.md
    - Quickstart (Streaming):
      - get-started/streaming/index.md
      - Python: get-started/streaming/quickstart-streaming.md
      - Java: get-started/streaming/quickstart-streaming-java.md
    - Testing: get-started/testing.md
    - Sample agents: https://github.com/google/adk-samples
    - About ADK: get-started/about.md
  - Tutorials:
    - tutorials/index.md
    - Agent Team: tutorials/agent-team.md
  - Agents:
    - agents/index.md
    - LLM agents: agents/llm-agents.md
    - Workflow agents:
      - agents/workflow-agents/index.md
      - Sequential agents: agents/workflow-agents/sequential-agents.md
      - Loop agents: agents/workflow-agents/loop-agents.md
      - Parallel agents: agents/workflow-agents/parallel-agents.md
    - Custom agents: agents/custom-agents.md
    - Multi-agent systems: agents/multi-agents.md
    - Models & Authentication: agents/models.md
  - Tools:
    - tools/index.md
    - Function tools: tools/function-tools.md
    - Built-in tools: tools/built-in-tools.md
    - Third party tools: tools/third-party-tools.md
    - Google Cloud tools: tools/google-cloud-tools.md
    - MCP tools: tools/mcp-tools.md
    - OpenAPI tools: tools/openapi-tools.md
    - Authentication: tools/authentication.md
    - Parallel Tool Execution: tools/parallel_tool_execution.md
    - Enterprise Web Search: tools/enterprise_web_search.md
  - Running Agents:
    - Agent Runtime: runtime/index.md
    - Runtime Config: runtime/runconfig.md
  - Deploy:
    - deploy/index.md
    - Agent Engine: deploy/agent-engine.md
    - Cloud Run: deploy/cloud-run.md
    - GKE: deploy/gke.md
  - Sessions & Memory:
    - sessions/index.md
    - Session: sessions/session.md
    - State: sessions/state.md
    - Memory: sessions/memory.md
    - Vertex AI Express Mode: sessions/express-mode.md
  - Callbacks:
    - callbacks/index.md
    - Types of callbacks: callbacks/types-of-callbacks.md
    - Callback patterns: callbacks/design-patterns-and-best-practices.md
  - Artifacts:
    - artifacts/index.md
  - Events:
    - events/index.md
  - Context:
    - context/index.md
  - Observability:
    - Logging: observability/logging.md
    - Cloud Trace: observability/cloud-trace.md
    - AgentOps: observability/agentops.md
    - Arize AX: observability/arize-ax.md
    - Phoenix: observability/phoenix.md
    - W&B Weave: observability/weave.md
  - Evaluate:
    - evaluate/index.md
  - MCP:
    - mcp/index.md
  - Bidi-streaming (live):
    - streaming/index.md
    - Quickstart (Bidi-streaming/live): get-started/streaming/index.md
    - Custom Audio Bidi-streaming app sample (SSE): streaming/custom-streaming.md
    - Custom Audio Bidi-streaming app sample (WebSockets): streaming/custom-streaming-ws.md
    - Bidi-streaming development guide series: streaming/dev-guide/part1.md
    - Streaming Tools: streaming/streaming-tools.md
    - Configurating Bidi-streaming behaviour: streaming/configuration.md
    - Google ADK + Vertex AI Live API (blog post): https://medium.com/google-cloud/google-adk-vertex-ai-live-api-125238982d5e
  - Grounding:
    - Understanding Google Search Grounding: grounding/google_search_grounding.md
    - Understanding Vertex AI Search Grounding: grounding/vertex_ai_search_grounding.md
  - Safety and Security: safety/index.md
  - A2A Protocol:
    - a2a/index.md
    - Introduction to A2A: a2a/intro.md
    - A2A Quickstart (Exposing): a2a/quickstart-exposing.md
    - A2A Quickstart (Consuming): a2a/quickstart-consuming.md
    - A2A Protocol Documentation: https://a2a-protocol.org
  - Community Resources: community.md
  - Contributing Guide: contributing-guide.md
  - API Reference:
    - api-reference/index.md
    - Python ADK: api-reference/python/index.html
    - Java ADK: api-reference/java/index.html
